name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Upload HTML to AWS
      run: |
        export VERSION=$(node -e "console.log(require('./package.json').version.replaceAll('-', '~').replaceAll('.', '-'))")
        yarn
        yarn build
        echo rm
        # aws s3 rm --recursive s3://alshdavid-public/rpc/latest
        echo cp1
        aws s3 cp ./dist/umd/index.js s3://alshdavid-public/rpc/latest.js
        echo cp2
        aws s3 cp ./dist/umd/index.js s3://alshdavid-public/rpc/${VERSION}.js
        echo cf1
        aws cloudfront create-invalidation --distribution-id E2QHY39OWRUCEU --paths /latest.js
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}